const linuxBootArray = [
  '[  OK  ] Finished Tell Plymouth To Write Out Runtime Data.',
  '[  OK  ] Finished Create Volatile Files and Directories.',
  '         Starting Network Name Resolution...',
  '         Starting Network Time Synchronization...',
  '         Starting Update UTMP about System Boot/Shutdown...',
  '[  OK  ] Finished Update UTMP about System Boot/Shutdown.',
  '[  OK  ] Finished Load AppArmor profiles.',
  '         Starting Raise network interfaces...',
  '         Starting Load AppArmor profiles managed internally by snapd...',
  '[  OK  ] Finished Load AppArmor profiles managed internally by snapd.',
  '[  OK  ] Finished Raise network interfaces.',
  '[  OK  ] Started Network Time Synchronization.',
  '[  OK  ] Reached target System Initialization.',
  '[  OK  ] Started ACPI Events Check.',
  '[  OK  ] Started CUPS Scheduler.',
  '[  OK  ] Started Daily Cleanup of Temporary Directories.',
  '[  OK  ] Reached target Paths.',
  '[  OK  ] Reached target System Time Set.',
  '[  OK  ] Reached target System Time Synchronized.',
  '[  OK  ] Started Trigger anacron every hour.',
  '[  OK  ] Started Daily apt download activities.',
  '[  OK  ] Started Daily apt upgrade and clean activities.',
  '[  OK  ] Started Periodic ext4 Online Metadata Check for All Filesystems.',
  '[  OK  ] Started Discard unused blocks once a week.',
  '[  OK  ] Started Refresh fwupd metadata regularly.',
  '[  OK  ] Started Daily rotation of log files.',
  '[  OK  ] Started Daily man-db regeneration.',
  '[  OK  ] Started Message of the Day.',
  '[  OK  ] Started Clean PHP session files every 30 mins.',
  '[  OK  ] Started Ubuntu Advantage update messaging.',
  '[  OK  ] Reached target Timers.',
  '[  OK  ] Listening on ACPID Listen Socket.',
  '[  OK  ] Listening on Avahi mDNS/DNS-SD Stack Activation Socket.',
  '[  OK  ] Listening on CUPS Scheduler.',
  '[  OK  ] Listening on D-Bus System Message Bus Socket.',
  '         Starting Socket activation for snappy daemon.',
  '[  OK  ] Listening on UUID daemon activation socket.',
  '[  OK  ] Listening on Socket activation for snappy daemon.',
  '[  OK  ] Reached target Sockets.',
  '[  OK  ] Reached target Basic System.',
  '         Starting Accounts Service...',
  '[  OK  ] Started ACPI event daemon.',
  '         Starting Save/Restore Sound Card State...',
  '[  OK  ] Started Run anacron jobs.',
  '         Starting Avahi mDNS/DNS-SD Stack...',
  '         Starting Bluetooth service...',
  '[  OK  ] Started Regular background program processing daemon.',
  '[  OK  ] Started CUPS Scheduler.',
  '[  OK  ] Started D-Bus System Message Bus.',
  '         Starting Network Manager...',
  '[  OK  ] Started Save initial kernel messages after boot.',
  '         Starting Remove Stale Online ext4 Metadata Check Snapshots...',
  '         Starting Detect the available GPUs and deal with any system changes...',
  '         Starting LSB: Record successful boot for GRUB...',
  '         Starting LSB: disk temperature monitoring daemon...',
  '[  OK  ] Started irqbalance daemon.',
  '         Starting Initialize hardware monitoring sensors...',
  '[  OK  ] Started mintsystem.service.',
  '         Starting Dispatcher daemon for systemd-networkd...',
  '[  OK  ] Started Set the CPU Frequency Scaling governor.',
  '         Starting Clean php session files...',
  '         Starting Authorization Manager...',
  '         Starting Restore /etc/resolv.conf if the system crashed before the ppp link was shut down...',
  '         Starting System Logging Service...',
  '         Starting Snap Daemon...',
  '         Starting Login Service...',
  '         Starting Thermal Daemon Service...',
  '         Starting Ubuntu system adjustments...',
  '         Starting Disk Manager...',
  '         Starting WPA supplicant...',
  '[  OK  ] Started Network Name Resolution.',
  '[  OK  ] Finished Remove Stale Online ext4 Metadata Check Snapshots.',
  '[  OK  ] Finished Restore /etc/resolv.conf if the system crashed before the ppp link was shut down.',
  '[  OK  ] Finished Save/Restore Sound Card State.',
  '[  OK  ] Started System Logging Service.',
  '[  OK  ] Reached target Host and Network Name Lookups.',
  '[  OK  ] Reached target Sound Card.',
  '         Starting Tool to automatically collect and submit kernel crash signatures...',
  '[  OK  ] Started LSB: disk temperature monitoring daemon.',
  '[  OK  ] Finished Initialize hardware monitoring sensors.',
  '[  OK  ] Started LSB: Record successful boot for GRUB.',
  '         Starting GRUB failed boot detection...',
  '[  OK  ] Started Tool to automatically collect and submit kernel crash signatures.',
  '[  OK  ] Finished GRUB failed boot detection.',
  '[  OK  ] Started Avahi mDNS/DNS-SD Stack.',
  '[  OK  ] Started Make remote CUPS printers available locally.',
  '[  OK  ] Started WPA supplicant.',
  '[  OK  ] Started Bluetooth service.',
  '[  OK  ] Started Thermal Daemon Service.',
  '[  OK  ] Reached target Bluetooth.',
  '[  OK  ] Started Authorization Manager.',
  '         Starting Modem Manager...',
  '[  OK  ] Started Network Manager.',
  '[  OK  ] Reached target Network.',
  '         Starting The Apache HTTP Server...',
  '         Starting MySQL Community Server...',
  '         Starting OpenVPN service...',
  '         Starting Hostname Service...',
  '         Starting Permit User Sessions...',
  '[  OK  ] Finished OpenVPN service.',
  '[  OK  ] Finished Permit User Sessions.',
  '         Starting Hold until boot process finishes up...',
  '[  OK  ] Finished Detect the available GPUs and deal with any system changes.',
  '         Starting Light Display Manager...',
  '[  OK  ] Started Accounts Service.',
  '[  OK  ] Finished Ubuntu system adjustments.',
  '[  OK  ] Started Modem Manager.',
  '[  OK  ] Started Hostname Service.',
  '         Starting Network Manager Script Dispatcher Service...',
  '[  OK  ] Started Network Manager Script Dispatcher Service.',
  '[  OK  ] Started Disk Manager.',
  '[  OK  ] Finished Clean php session files.',
  '         Starting NVIDIA Persistence Daemon...',
  '[  OK  ] Started NVIDIA Persistence Daemon.',
  '[  OK  ] Started Dispatcher daemon for systemd-networkd.',
  '[  OK  ] Started The Apache HTTP Server.',
  '[  OK  ] Started Login Service.',
];

const randomTime = (num) => {
  return Math.floor(Math.random() * num + 1);
};

for (let i = 0; i < linuxBootArray.length; i++) {
  setTimeout(() => {
    console.log(linuxBootArray[i]);
  }, randomTime(5000));
}
